type WallaBagTag = {
    id: number,
    label: string,
    slug: string,
}

export interface WallaBagArticle {
    is_archived: number,
    is_starred: number,
    user_name: string,
    user_email: string,
    user_id: 1,
    tags: WallaBagTag[],
    is_public: boolean,
    id: number,
    uid: null,
    title: string,
    url: string,
    hashed_url: string,
    origin_url: string | null,
    given_url: string,
    hashed_given_url: string,
    archived_at: string,
    content: string,
    created_at: string,
    updated_at: string,
    published_at: string | null,
    published_by: string[],
    starred_at: string | null,
    annotations: any[],
    mimetype: string,
    language: string | null,
    reading_time: number,
    domain_name: string,
    preview_picture: string,
    http_status: number,
}